title: CNE23 Sem01
description: The first semseter of the 23rd edition of the CNE.
theme: just-the-docs

url: https://cloud-native-engineering.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
